[mcp_servers.ai-game-developer]
enabled = true
startup_timeout_sec = 30
tool_timeout_sec = 300
url = "http://localhost:21678"
[mcp_servers.ai-game-developer.tools.assets-refresh]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-create]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-modify]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-component-add]
approval_mode = "approve"

[mcp_servers.ai-game-developer.tools.gameobject-modify]
approval_mode = "approve"
